<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>$(AnalyzerTargetFrameworks)</TargetFrameworks>
    <RootNamespace>Lytec.AvaloniaUI.Generators</RootNamespace>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <NoWarn>$(NoWarn);NU5128</NoWarn>
  </PropertyGroup>

  <Import Project="..\Analyzer.References.props" />

  <ItemGroup>
    <None Include="README.md" Pack="true" PackagePath="\" />
  </ItemGroup>

</Project>
