<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net472</TargetFramework>
  </PropertyGroup>

  <Import Project="..\Test.References.props" />

  <ItemGroup>
    <ProjectReference Include="..\WinForms\Lytec.WinForms.csproj" />
    <ProjectReference Include="..\Image.GDIPlus\Lytec.Image.GDIPlus.csproj" />
  </ItemGroup>

</Project>
