<?xml version="1.0" encoding="utf-8"?>
<Project>

  <PropertyGroup>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild> <!-- Generates a package at build -->
    <IncludeBuildOutput>false</IncludeBuildOutput> <!-- Do not include the generator as a lib dependency -->
    <SuppressDependenciesWhenPacking>true</SuppressDependenciesWhenPacking>
    <OutputItemType>Analyzer</OutputItemType>
    <IsPackable>true</IsPackable>
    <EnforceExtendedAnalyzerRules>true</EnforceExtendedAnalyzerRules>
    <IsRoslynComponent>true</IsRoslynComponent>

  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.CodeAnalysis" PrivateAssets="all" />
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp" PrivateAssets="all" />
    <PackageReference Include="Costura.Fody">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>compile; runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.CodeAnalysis.Analyzers">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <PropertyGroup>
    <TargetsForTfmSpecificContentInPackage>$(TargetsForTfmSpecificContentInPackage);PackGeneratorAssembly</TargetsForTfmSpecificContentInPackage>
  </PropertyGroup>

  <!-- 在目标框架上下文中添加生成器，避免多目标项目的输出路径不完整。 -->
  <Target Name="PackGeneratorAssembly">
    <ItemGroup>
      <TfmSpecificPackageFile Include="$(TargetPath)"
                              PackagePath="analyzers/dotnet/cs"
                              BuildAction="Analyzer" />
    </ItemGroup>
  </Target>
</Project>
