using System.Collections.Immutable;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace Lytec.AvaloniaUI.Generators;

[Generator]
public sealed class ControlFactoryGenerator : IIncrementalGenerator
{
    private const string GenerateAttributeName =
        "Lytec.AvaloniaUI.Generators.GenerateControlFactoriesAttribute";
    private const string IncludeAttributeName =
        "Lytec.AvaloniaUI.Generators.IncludeControlFactoryAttribute";
    private const string ControlTypeName = "Avalonia.Controls.Control";
    private const string ViewBaseTypeName = "Avalonia.Markup.Declarative.ViewBase";
    private const string ContentAttributeName = "Avalonia.Metadata.ContentAttribute";

    private static readonly DiagnosticDescriptor TargetMustBePartial = new(
        "LYAVGEN001",
        "Control factory target must be partial",
        "Type '{0}' and all of its containing types must be partial",
        "Usage",
        DiagnosticSeverity.Error,
        true);

    private static readonly DiagnosticDescriptor TargetMustDeriveFromViewBase = new(
        "LYAVGEN002",
        "Invalid control factory target",
        "Type '{0}' must derive from Avalonia.Markup.Declarative.ViewBase",
        "Usage",
        DiagnosticSeverity.Error,
        true);

    private static readonly DiagnosticDescriptor InvalidIncludedControl = new(
        "LYAVGEN003",
        "Invalid included control",
        "Type '{0}' must be an accessible, non-abstract Control with a public zero-argument constructor",
        "Usage",
        DiagnosticSeverity.Error,
        true);

    private static readonly DiagnosticDescriptor InvalidAlias = new(
        "LYAVGEN004",
        "Invalid control factory alias",
        "Alias '{0}' for control '{1}' is not a valid C# identifier",
        "Usage",
        DiagnosticSeverity.Error,
        true);

    private static readonly DiagnosticDescriptor InvalidPrimaryProperty = new(
        "LYAVGEN005",
        "Invalid primary control property",
        "Primary property '{0}' on control '{1}' is not supported by the current Declarative-style factory rules",
        "Usage",
        DiagnosticSeverity.Error,
        true);

    private static readonly DiagnosticDescriptor FactoryNameConflict = new(
        "LYAVGEN006",
        "Control factory name conflict",
        "Factory name '{0}' is used by both '{1}' and '{2}'; configure an Alias to resolve the conflict",
        "Usage",
        DiagnosticSeverity.Error,
        true);

    private static readonly DiagnosticDescriptor ExistingMemberConflictDiagnostic = new(
        "LYAVGEN007",
        "Control factory conflicts with an existing member",
        "Factory '{0}' for control '{1}' conflicts with existing member '{2}'; configure an Alias or rename the member",
        "Usage",
        DiagnosticSeverity.Error,
        true);

    private static readonly DiagnosticDescriptor ThirdPartyPrimaryPropertyNotFound = new(
        "LYAVGEN008",
        "No primary property inferred for included control",
        "No primary property could be inferred for included control '{0}'; only the parameterless factory will be generated",
        "Usage",
        DiagnosticSeverity.Warning,
        true);

    private static readonly SymbolDisplayFormat TypeDisplayFormat =
        SymbolDisplayFormat.FullyQualifiedFormat.WithMiscellaneousOptions(
            SymbolDisplayFormat.FullyQualifiedFormat.MiscellaneousOptions |
            SymbolDisplayMiscellaneousOptions.UseSpecialTypes |
            SymbolDisplayMiscellaneousOptions.IncludeNullableReferenceTypeModifier);

    private static readonly string AttributeSource = """
        // <auto-generated />
        #nullable enable

        namespace Lytec.AvaloniaUI.Generators
        {
            [global::System.AttributeUsage(
                global::System.AttributeTargets.Class,
                AllowMultiple = false,
                Inherited = false)]
            public sealed class GenerateControlFactoriesAttribute : global::System.Attribute
            {
            }

            [global::System.AttributeUsage(
                global::System.AttributeTargets.Class,
                AllowMultiple = true,
                Inherited = false)]
            public sealed class IncludeControlFactoryAttribute : global::System.Attribute
            {
                public IncludeControlFactoryAttribute(global::System.Type controlType)
                {
                    ControlType = controlType;
                }

                public global::System.Type ControlType { get; }

                public string? PrimaryProperty { get; set; }

                public string? Alias { get; set; }
            }
        }
        """;

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterPostInitializationOutput(static output =>
            output.AddSource(
                "ControlFactoryAttributes.g.cs",
                SourceText.From(AttributeSource, Encoding.UTF8)));

        var targets = context.SyntaxProvider.ForAttributeWithMetadataName(
            GenerateAttributeName,
            static (node, _) => node is ClassDeclarationSyntax,
            static (attributeContext, _) => (INamedTypeSymbol)attributeContext.TargetSymbol);

        context.RegisterSourceOutput(
            context.CompilationProvider.Combine(targets.Collect()),
            static (output, source) => Generate(output, source.Left, source.Right));
    }

    private static void Generate(
        SourceProductionContext context,
        Compilation compilation,
        ImmutableArray<INamedTypeSymbol> rawTargets)
    {
        if (rawTargets.IsDefaultOrEmpty)
            return;

        var controlType = compilation.GetTypeByMetadataName(ControlTypeName);
        var viewBaseType = compilation.GetTypeByMetadataName(ViewBaseTypeName);
        if (controlType is null || viewBaseType is null)
            return;

        var officialControls = DiscoverOfficialControls(compilation, controlType);
        var targets = rawTargets
            .Distinct<INamedTypeSymbol>(SymbolEqualityComparer.Default)
            .OrderBy(static target => target.ToDisplayString(), StringComparer.Ordinal);

        foreach (var target in targets)
        {
            var targetLocation = GetLocation(target);
            if (!IsPartialTypeChain(target))
            {
                context.ReportDiagnostic(Diagnostic.Create(
                    TargetMustBePartial,
                    targetLocation,
                    target.ToDisplayString()));
                continue;
            }

            if (!IsOrDerivesFrom(target, viewBaseType))
            {
                context.ReportDiagnostic(Diagnostic.Create(
                    TargetMustDeriveFromViewBase,
                    targetLocation,
                    target.ToDisplayString()));
                continue;
            }

            var specifications = BuildSpecifications(
                context,
                target,
                officialControls,
                controlType);
            if (specifications.Count == 0)
                continue;

            var resolved = ResolveNameConflicts(context, target, specifications);
            if (resolved.Count == 0)
                continue;

            var source = GenerateTargetSource(context, target, resolved);
            if (source is null)
                continue;

            context.AddSource(
                target.ToDisplayString().Replace('<', '_').Replace('>', '_') +
                ".ControlFactories.g.cs",
                SourceText.From(source, Encoding.UTF8));
        }
    }

    private static IReadOnlyList<ControlSpecification> BuildSpecifications(
        SourceProductionContext context,
        INamedTypeSymbol target,
        IReadOnlyList<INamedTypeSymbol> officialControls,
        INamedTypeSymbol controlType)
    {
        var specifications = new Dictionary<INamedTypeSymbol, ControlSpecification>(
            SymbolEqualityComparer.Default);

        foreach (var control in officialControls)
        {
            specifications[control] = new ControlSpecification(
                control,
                control.Name,
                null,
                false,
                false,
                GetLocation(target));
        }

        foreach (var attribute in target.GetAttributes().Where(static attribute =>
                     attribute.AttributeClass?.ToDisplayString() == IncludeAttributeName))
        {
            var location = attribute.ApplicationSyntaxReference?
                .GetSyntax(context.CancellationToken)
                .GetLocation() ?? GetLocation(target);
            var includedType = attribute.ConstructorArguments.Length > 0
                ? attribute.ConstructorArguments[0].Value as INamedTypeSymbol
                : null;

            if (includedType is null ||
                !IsUsableControl(includedType, controlType))
            {
                context.ReportDiagnostic(Diagnostic.Create(
                    InvalidIncludedControl,
                    location,
                    includedType?.ToDisplayString() ?? "<unknown>"));
                continue;
            }

            var alias = GetNamedString(attribute, "Alias") ?? includedType.Name;
            if (!SyntaxFacts.IsValidIdentifier(alias))
            {
                context.ReportDiagnostic(Diagnostic.Create(
                    InvalidAlias,
                    location,
                    alias,
                    includedType.ToDisplayString()));
                continue;
            }

            specifications[includedType] = new ControlSpecification(
                includedType,
                alias,
                GetNamedString(attribute, "PrimaryProperty"),
                !IsOfficialAvaloniaAssembly(includedType.ContainingAssembly),
                true,
                location);
        }

        return specifications.Values
            .OrderBy(static specification => specification.FactoryName, StringComparer.Ordinal)
            .ThenBy(static specification => specification.Control.ToDisplayString(), StringComparer.Ordinal)
            .ToArray();
    }

    private static IReadOnlyList<ControlSpecification> ResolveNameConflicts(
        SourceProductionContext context,
        INamedTypeSymbol target,
        IReadOnlyList<ControlSpecification> specifications)
    {
        var result = new List<ControlSpecification>();
        foreach (var group in specifications.GroupBy(
                     static specification => specification.FactoryName,
                     StringComparer.Ordinal))
        {
            var distinctControls = group
                .Select(static specification => specification.Control)
                .Distinct<INamedTypeSymbol>(SymbolEqualityComparer.Default)
                .ToArray();
            if (distinctControls.Length > 1)
            {
                var first = distinctControls[0];
                foreach (var control in distinctControls.Skip(1))
                {
                    context.ReportDiagnostic(Diagnostic.Create(
                        FactoryNameConflict,
                        group.FirstOrDefault(static item => item.IsExplicit)?.Location ??
                        GetLocation(target),
                        group.Key,
                        first.ToDisplayString(),
                        control.ToDisplayString()));
                }

                continue;
            }

            var specification = group.First();
            var conflict = FindExistingNonMethodConflict(target, specification.FactoryName);
            if (conflict is not null)
            {
                // A framework control can share its name with an inherited ViewBase
                // member (ContextMenu is the common example). Skip that optional
                // convenience factory; users can opt it back in under an alias.
                if (!specification.IsExplicit)
                    continue;

                context.ReportDiagnostic(Diagnostic.Create(
                    ExistingMemberConflictDiagnostic,
                    specification.Location,
                    specification.FactoryName,
                    specification.Control.ToDisplayString(),
                    conflict.ToDisplayString()));
                continue;
            }

            result.Add(specification);
        }

        return result;
    }

    private static string? GenerateTargetSource(
        SourceProductionContext context,
        INamedTypeSymbol target,
        IReadOnlyList<ControlSpecification> specifications)
    {
        var factories = new List<FactoryDefinition>();
        foreach (var specification in specifications)
        {
            var primary = ResolvePrimaryProperty(specification);
            if (specification.PrimaryProperty is not null && primary is null)
            {
                context.ReportDiagnostic(Diagnostic.Create(
                    InvalidPrimaryProperty,
                    specification.Location,
                    specification.PrimaryProperty,
                    specification.Control.ToDisplayString()));
                continue;
            }

            if (primary is null && specification.IsThirdParty)
            {
                context.ReportDiagnostic(Diagnostic.Create(
                    ThirdPartyPrimaryPropertyNotFound,
                    specification.Location,
                    specification.Control.ToDisplayString()));
            }

            var factory = CreateFactoryDefinition(context, target, specification, primary);
            if (factory is not null)
                factories.Add(factory);
        }

        if (factories.Count == 0)
            return null;

        var builder = new StringBuilder();
        builder.AppendLine("// <auto-generated />");
        builder.AppendLine("#nullable enable");
        builder.AppendLine();

        var namespaceName = target.ContainingNamespace.IsGlobalNamespace
            ? null
            : target.ContainingNamespace.ToDisplayString();
        if (namespaceName is not null)
        {
            builder.Append("namespace ").Append(namespaceName).AppendLine();
            builder.AppendLine("{");
        }

        var typeChain = GetTypeChain(target);
        var namespaceIndent = namespaceName is null ? 0 : 1;
        for (var index = 0; index < typeChain.Count; index++)
        {
            AppendIndent(builder, namespaceIndent + index);
            builder.Append(GetTypeDeclaration(typeChain[index])).AppendLine();
            AppendTypeConstraints(builder, typeChain[index], namespaceIndent + index + 1);
            AppendIndent(builder, namespaceIndent + index);
            builder.AppendLine("{");
        }

        var memberIndent = namespaceIndent + typeChain.Count;
        foreach (var factory in factories)
            AppendFactory(builder, factory, memberIndent);

        for (var index = typeChain.Count - 1; index >= 0; index--)
        {
            AppendIndent(builder, namespaceIndent + index);
            builder.AppendLine("}");
        }

        if (namespaceName is not null)
            builder.AppendLine("}");

        builder.AppendLine("#nullable restore");
        return CSharpSyntaxTree.ParseText(builder.ToString())
            .GetRoot()
            .NormalizeWhitespace()
            .ToFullString();
    }

    private static void AppendFactory(
        StringBuilder builder,
        FactoryDefinition factory,
        int indent)
    {
        var controlType = GetTypeName(factory.Specification.Control);
        var factoryName = EscapeIdentifier(factory.Specification.FactoryName);

        if (factory.GenerateParameterless)
        {
            AppendIndent(builder, indent);
            builder.Append("public static ")
                .Append(controlType)
                .Append(' ')
                .Append(factoryName)
                .AppendLine("()");
            AppendIndent(builder, indent + 1);
            builder.Append("=> new ").Append(controlType).AppendLine("();");
            builder.AppendLine();
        }

        if (factory.Primary is null)
            return;

        switch (factory.Primary.Kind)
        {
            case PrimaryPropertyKind.Children:
                if (factory.GenerateCollection)
                {
                    AppendCollectionFactory(
                        builder,
                        indent,
                        controlType,
                        factoryName,
                        "global::Avalonia.Controls.Control[]",
                        "children",
                        "Children");
                }
                break;
            case PrimaryPropertyKind.Items:
                if (factory.GenerateCollection)
                {
                    AppendCollectionFactory(
                        builder,
                        indent,
                        controlType,
                        factoryName,
                        "global::Avalonia.AvaloniaObject[]",
                        "items",
                        "Items");
                }
                break;
            case PrimaryPropertyKind.Regular:
                AppendPropertyFactories(
                    builder,
                    indent,
                    controlType,
                    factoryName,
                    factory.Primary,
                    factory.GenerateValue,
                    factory.GenerateBinding,
                    factory.GenerateCompiledBinding);
                break;
        }
    }

    private static void AppendCollectionFactory(
        StringBuilder builder,
        int indent,
        string controlType,
        string factoryName,
        string elementArrayType,
        string parameterName,
        string extensionName)
    {
        AppendIndent(builder, indent);
        builder.Append("public static ")
            .Append(controlType)
            .Append(' ')
            .Append(factoryName)
            .Append("(params ")
            .Append(elementArrayType)
            .Append(' ')
            .Append(parameterName)
            .AppendLine(")");
        AppendIndent(builder, indent + 1);
        builder.Append("=> global::Avalonia.Markup.Declarative.ControlPropertyExtensions.")
            .Append(extensionName)
            .Append("(new ")
            .Append(controlType)
            .Append("(), ")
            .Append(parameterName)
            .AppendLine(");");
        builder.AppendLine();
    }

    private static void AppendPropertyFactories(
        StringBuilder builder,
        int indent,
        string controlType,
        string factoryName,
        PrimaryProperty primary,
        bool generateValue,
        bool generateBinding,
        bool generateCompiledBinding)
    {
        var property = primary.Property!;
        var valueType = GetTypeName(property.Type);
        var parameterName = ToCamelCase(property.Name);
        var escapedPropertyName = EscapeIdentifier(property.Name);
        var avaloniaProperty = GetTypeName(primary.AvaloniaProperty!.ContainingType) + "." +
                              EscapeIdentifier(primary.AvaloniaProperty.Name);

        if (generateValue)
        {
            AppendIndent(builder, indent);
            builder.Append("public static ")
                .Append(controlType)
                .Append(' ')
                .Append(factoryName)
                .Append('(')
                .Append(valueType)
                .Append(' ')
                .Append(parameterName)
                .AppendLine(",");
            AppendCallerParameters(builder, indent + 1);
            AppendIndent(builder, indent);
            builder.AppendLine(")");
            AppendIndent(builder, indent + 1);
            builder.AppendLine("{");
            AppendIndent(builder, indent + 2);
            builder.Append("var control = new ").Append(controlType).AppendLine("();");
            AppendIndent(builder, indent + 2);
            builder.Append("return global::Avalonia.Markup.Declarative.ControlPropertyExtensions._set(")
                .Append("control, () => control.")
                .Append(escapedPropertyName)
                .Append(" = ")
                .Append(parameterName)
                .AppendLine("!, _callerFile, _callerLine);");
            AppendIndent(builder, indent + 1);
            builder.AppendLine("}");
            builder.AppendLine();
        }

        if (generateBinding)
        {
            AppendIndent(builder, indent);
            builder.Append("public static ")
                .Append(controlType)
                .Append(' ')
                .Append(factoryName)
                .AppendLine("(");
            AppendIndent(builder, indent + 1);
            builder.AppendLine("global::Avalonia.Data.BindingBase binding,");
            AppendCallerParameters(builder, indent + 1);
            AppendIndent(builder, indent);
            builder.AppendLine(")");
            AppendIndent(builder, indent + 1);
            builder.Append("=> global::Avalonia.Markup.Declarative.ControlPropertyExtensions.BindValue(")
                .Append("new ")
                .Append(controlType)
                .Append("(), ")
                .Append(avaloniaProperty)
                .AppendLine("!, binding, _callerFile, _callerLine);");
            builder.AppendLine();
        }

        if (generateCompiledBinding)
        {
            AppendIndent(builder, indent);
            builder.Append("public static ")
                .Append(controlType)
                .Append(' ')
                .Append(factoryName)
                .AppendLine("<TViewModel, TValue>(");
            AppendIndent(builder, indent + 1);
            builder.AppendLine("TViewModel source,");
            AppendIndent(builder, indent + 1);
            builder.AppendLine("global::System.Linq.Expressions.Expression<global::System.Func<TViewModel, TValue>> getter,");
            AppendIndent(builder, indent + 1);
            builder.AppendLine("global::Avalonia.Data.BindingMode? mode = null,");
            AppendIndent(builder, indent + 1);
            builder.AppendLine("global::Avalonia.Data.Converters.IValueConverter? converter = null,");
            AppendCallerParameters(builder, indent + 1);
            AppendIndent(builder, indent);
            builder.AppendLine(")");
            AppendIndent(builder, indent + 1);
            builder.Append("=> global::Avalonia.Markup.Declarative.ControlPropertyExtensions._setCompiledBinding(")
                .Append("new ")
                .Append(controlType)
                .Append("(), ")
                .Append(avaloniaProperty)
                .AppendLine("!, source, getter, mode, converter, _callerFile, _callerLine);");
            builder.AppendLine();
        }
    }

    private static void AppendCallerParameters(StringBuilder builder, int indent)
    {
        AppendIndent(builder, indent);
        builder.AppendLine("[global::System.Runtime.CompilerServices.CallerFilePath] string? _callerFile = null,");
        AppendIndent(builder, indent);
        builder.Append("[global::System.Runtime.CompilerServices.CallerLineNumber] int _callerLine = 0");
    }

    private static PrimaryProperty? ResolvePrimaryProperty(ControlSpecification specification)
    {
        if (specification.PrimaryProperty is not null)
            return TryCreatePrimary(specification.Control, specification.PrimaryProperty);

        foreach (var rule in SemanticRules)
        {
            if (IsOrDerivesFrom(specification.Control, rule.TypeName))
            {
                var primary = TryCreatePrimary(specification.Control, rule.PropertyName);
                if (primary is not null)
                    return primary;
            }
        }

        foreach (var type in GetBaseTypesAndSelf(specification.Control))
        {
            var contentProperties = type.GetMembers()
                .OfType<IPropertySymbol>()
                .Where(static property => !property.IsStatic)
                .Where(static property => property.GetAttributes().Any(attribute =>
                    attribute.AttributeClass?.ToDisplayString() == ContentAttributeName))
                .ToArray();
            if (contentProperties.Length != 1)
                continue;

            var primary = TryCreatePrimary(specification.Control, contentProperties[0].Name);
            if (primary is not null)
                return primary;
        }

        return null;
    }

    private static PrimaryProperty? TryCreatePrimary(
        INamedTypeSymbol control,
        string propertyName)
    {
        if (propertyName == "Children" &&
            IsOrDerivesFrom(control, "Avalonia.Controls.Panel"))
        {
            return new PrimaryProperty(PrimaryPropertyKind.Children, null, null);
        }

        if (propertyName == "Items" &&
            IsOrDerivesFrom(control, "Avalonia.Controls.ItemsControl"))
        {
            return new PrimaryProperty(PrimaryPropertyKind.Items, null, null);
        }

        var property = GetBaseTypesAndSelf(control)
            .SelectMany(static type => type.GetMembers())
            .OfType<IPropertySymbol>()
            .FirstOrDefault(property =>
                property.Name == propertyName &&
                !property.IsStatic &&
                property.DeclaredAccessibility == Accessibility.Public &&
                property.SetMethod?.DeclaredAccessibility == Accessibility.Public);
        if (property is null)
            return null;

        var avaloniaProperty = GetBaseTypesAndSelf(property.ContainingType)
            .SelectMany(type => type.GetMembers(property.Name + "Property"))
            .FirstOrDefault(member =>
                member.IsStatic &&
                member.DeclaredAccessibility == Accessibility.Public &&
                member is IFieldSymbol or IPropertySymbol);
        if (avaloniaProperty is null)
            return null;

        return new PrimaryProperty(
            PrimaryPropertyKind.Regular,
            property,
            avaloniaProperty);
    }

    private static readonly SemanticRule[] SemanticRules =
    [
        new("Avalonia.Controls.Primitives.HeaderedContentControl", "Header"),
        new("Avalonia.Controls.Primitives.HeaderedItemsControl", "Header"),
        new("Avalonia.Controls.Primitives.HeaderedSelectingItemsControl", "Header"),
        new("Avalonia.Controls.TextBlock", "Text"),
        new("Avalonia.Controls.TextBox", "Text"),
        new("Avalonia.Controls.Presenters.TextPresenter", "Text"),
        new("Avalonia.Controls.Primitives.AccessText", "Text"),
        new("Avalonia.Controls.AutoCompleteBox", "Text"),
        new("Avalonia.Controls.CalendarDatePicker", "Text"),
        new("Avalonia.Controls.Primitives.RangeBase", "Value"),
        new("Avalonia.Controls.NumericUpDown", "Value"),
        new("Avalonia.Controls.PathIcon", "Data"),
        new("Avalonia.Controls.Shapes.Path", "Data"),
    ];

    private static IReadOnlyList<INamedTypeSymbol> DiscoverOfficialControls(
        Compilation compilation,
        INamedTypeSymbol controlType)
    {
        var controls = new HashSet<INamedTypeSymbol>(SymbolEqualityComparer.Default);
        foreach (var assembly in compilation.SourceModule.ReferencedAssemblySymbols
                     .Where(IsOfficialAvaloniaAssembly))
        {
            AddNamespaceControls(assembly.GlobalNamespace, controls, controlType);
        }

        return controls
            .OrderBy(static control => control.ToDisplayString(), StringComparer.Ordinal)
            .ToArray();
    }

    private static void AddNamespaceControls(
        INamespaceSymbol namespaceSymbol,
        ISet<INamedTypeSymbol> controls,
        INamedTypeSymbol controlType)
    {
        foreach (var type in namespaceSymbol.GetTypeMembers())
            AddTypeAndNestedControls(type, controls, controlType);
        foreach (var childNamespace in namespaceSymbol.GetNamespaceMembers())
            AddNamespaceControls(childNamespace, controls, controlType);
    }

    private static void AddTypeAndNestedControls(
        INamedTypeSymbol type,
        ISet<INamedTypeSymbol> controls,
        INamedTypeSymbol controlType)
    {
        if (IsUsableControl(type, controlType))
            controls.Add(type);
        foreach (var nestedType in type.GetTypeMembers())
            AddTypeAndNestedControls(nestedType, controls, controlType);
    }

    private static bool IsOfficialAvaloniaAssembly(IAssemblySymbol assembly)
    {
        var name = assembly.Identity.Name;
        if (name != "Avalonia" && !name.StartsWith("Avalonia.", StringComparison.Ordinal))
            return false;

        var token = assembly.Identity.PublicKeyToken;
        return token.Length == 8 &&
               token[0] == 0xc8 && token[1] == 0xd4 &&
               token[2] == 0x84 && token[3] == 0xa7 &&
               token[4] == 0x01 && token[5] == 0x2f &&
               token[6] == 0x9a && token[7] == 0x8b;
    }

    private static bool IsUsableControl(
        INamedTypeSymbol type,
        INamedTypeSymbol controlType)
    {
        return type.TypeKind == TypeKind.Class &&
               !type.IsAbstract &&
               !type.IsGenericType &&
               IsAccessible(type) &&
               IsOrDerivesFrom(type, controlType) &&
               type.InstanceConstructors.Any(static constructor =>
                   constructor.DeclaredAccessibility == Accessibility.Public &&
                   constructor.Parameters.All(static parameter =>
                       parameter.IsOptional || parameter.IsParams)) &&
               !type.GetAttributes().Any(static attribute =>
                   attribute.AttributeClass?.ToDisplayString() == "System.ObsoleteAttribute");
    }

    private static bool IsAccessible(INamedTypeSymbol type)
    {
        for (var current = type; current is not null; current = current.ContainingType)
        {
            if (current.DeclaredAccessibility != Accessibility.Public)
                return false;
        }

        return true;
    }

    private static FactoryDefinition? CreateFactoryDefinition(
        SourceProductionContext context,
        INamedTypeSymbol target,
        ControlSpecification specification,
        PrimaryProperty? primary)
    {
        var variants = new List<FactoryVariant> { FactoryVariant.Parameterless };
        if (primary is not null)
        {
            if (primary.Kind is PrimaryPropertyKind.Children or PrimaryPropertyKind.Items)
                variants.Add(FactoryVariant.Collection);
            else
            {
                variants.Add(FactoryVariant.Value);
                variants.Add(FactoryVariant.Binding);
                variants.Add(FactoryVariant.CompiledBinding);
            }
        }

        var enabled = new HashSet<FactoryVariant>(variants);
        foreach (var variant in variants)
        {
            var existing = FindExistingFactoryMethod(
                target,
                specification.FactoryName,
                variant,
                primary);
            if (existing is null)
                continue;

            if (existing.IsStatic &&
                SymbolEqualityComparer.Default.Equals(
                    existing.ReturnType,
                    specification.Control))
            {
                enabled.Remove(variant);
                continue;
            }

            context.ReportDiagnostic(Diagnostic.Create(
                ExistingMemberConflictDiagnostic,
                specification.Location,
                specification.FactoryName,
                specification.Control.ToDisplayString(),
                existing.ToDisplayString()));
            return null;
        }

        if (enabled.Count == 0)
            return null;

        return new FactoryDefinition(
            specification,
            primary,
            enabled.Contains(FactoryVariant.Parameterless),
            enabled.Contains(FactoryVariant.Collection),
            enabled.Contains(FactoryVariant.Value),
            enabled.Contains(FactoryVariant.Binding),
            enabled.Contains(FactoryVariant.CompiledBinding));
    }

    private static ISymbol? FindExistingNonMethodConflict(
        INamedTypeSymbol target,
        string factoryName)
    {
        foreach (var type in GetBaseTypesAndSelf(target))
        {
            var member = type.GetMembers(factoryName)
                .FirstOrDefault(static member => member is not IMethodSymbol);
            if (member is not null)
                return member;
        }

        return null;
    }

    private static IMethodSymbol? FindExistingFactoryMethod(
        INamedTypeSymbol target,
        string factoryName,
        FactoryVariant variant,
        PrimaryProperty? primary)
    {
        foreach (var type in GetBaseTypesAndSelf(target))
        {
            foreach (var method in type.GetMembers(factoryName).OfType<IMethodSymbol>())
            {
                if (!SymbolEqualityComparer.Default.Equals(type, target) &&
                    method.DeclaredAccessibility == Accessibility.Private)
                    continue;
                if (MatchesFactoryVariant(method, variant, primary))
                    return method;
            }
        }

        return null;
    }

    private static bool MatchesFactoryVariant(
        IMethodSymbol method,
        FactoryVariant variant,
        PrimaryProperty? primary)
    {
        switch (variant)
        {
            case FactoryVariant.Parameterless:
                return method.Arity == 0 && method.Parameters.Length == 0;

            case FactoryVariant.Collection:
                if (method.Arity != 0 || method.Parameters.Length != 1)
                    return false;
                var expectedArray = primary?.Kind == PrimaryPropertyKind.Children
                    ? "global::Avalonia.Controls.Control[]"
                    : "global::Avalonia.AvaloniaObject[]";
                return GetTypeName(method.Parameters[0].Type) == expectedArray;

            case FactoryVariant.Value:
                return method.Arity == 0 &&
                       HasFactoryParameterShape(method, primary!.Property!.Type);

            case FactoryVariant.Binding:
                return method.Arity == 0 &&
                       method.Parameters.Length is 1 or 3 &&
                       method.Parameters[0].Type.ToDisplayString() ==
                       "Avalonia.Data.BindingBase" &&
                       HasOptionalCallerTail(method);

            case FactoryVariant.CompiledBinding:
                return method.Arity == 2 &&
                       method.Parameters.Length is 2 or 6 &&
                       method.Parameters[1].Type is INamedTypeSymbol expression &&
                       expression.OriginalDefinition.ToDisplayString() ==
                       "System.Linq.Expressions.Expression<TDelegate>" &&
                       (method.Parameters.Length == 2 || HasOptionalCallerTail(method));

            default:
                return false;
        }
    }

    private static bool HasFactoryParameterShape(
        IMethodSymbol method,
        ITypeSymbol valueType)
    {
        return method.Parameters.Length is 1 or 3 &&
               SymbolEqualityComparer.Default.Equals(method.Parameters[0].Type, valueType) &&
               HasOptionalCallerTail(method);
    }

    private static bool HasOptionalCallerTail(IMethodSymbol method)
    {
        if (method.Parameters.Length is 1 or 2)
            return true;
        if (method.Parameters.Length == 3)
        {
            return method.Parameters[1].Type.SpecialType == SpecialType.System_String &&
                   method.Parameters[2].Type.SpecialType == SpecialType.System_Int32;
        }

        if (method.Parameters.Length == 6)
        {
            return method.Parameters[4].Type.SpecialType == SpecialType.System_String &&
                   method.Parameters[5].Type.SpecialType == SpecialType.System_Int32;
        }

        return false;
    }

    private static string? GetNamedString(AttributeData attribute, string name)
    {
        foreach (var argument in attribute.NamedArguments)
        {
            if (argument.Key == name)
                return argument.Value.Value as string;
        }

        return null;
    }

    private static bool IsPartialTypeChain(INamedTypeSymbol type)
    {
        for (var current = type; current is not null; current = current.ContainingType)
        {
            if (current.DeclaringSyntaxReferences.Length == 0 ||
                current.DeclaringSyntaxReferences.Any(reference =>
                    reference.GetSyntax() is not TypeDeclarationSyntax declaration ||
                    !declaration.Modifiers.Any(SyntaxKind.PartialKeyword)))
            {
                return false;
            }
        }

        return true;
    }

    private static bool IsOrDerivesFrom(INamedTypeSymbol type, INamedTypeSymbol baseType)
    {
        for (var current = type; current is not null; current = current.BaseType)
        {
            if (SymbolEqualityComparer.Default.Equals(current, baseType) ||
                SymbolEqualityComparer.Default.Equals(current.OriginalDefinition, baseType))
            {
                return true;
            }
        }

        return false;
    }

    private static bool IsOrDerivesFrom(INamedTypeSymbol type, string metadataName)
    {
        for (var current = type; current is not null; current = current.BaseType)
        {
            if (current.ToDisplayString() == metadataName ||
                current.OriginalDefinition.ToDisplayString() == metadataName)
            {
                return true;
            }
        }

        return false;
    }

    private static IEnumerable<INamedTypeSymbol> GetBaseTypesAndSelf(INamedTypeSymbol type)
    {
        for (var current = type; current is not null; current = current.BaseType)
            yield return current;
    }

    private static IReadOnlyList<INamedTypeSymbol> GetTypeChain(INamedTypeSymbol type)
    {
        var result = new List<INamedTypeSymbol>();
        for (var current = type; current is not null; current = current.ContainingType)
            result.Add(current);
        result.Reverse();
        return result;
    }

    private static string GetTypeDeclaration(INamedTypeSymbol type)
    {
        var builder = new StringBuilder();
        builder.Append(GetAccessibility(type.DeclaredAccessibility));
        if (type.IsStatic)
            builder.Append("static ");
        else
        {
            if (type.IsAbstract)
                builder.Append("abstract ");
            if (type.IsSealed)
                builder.Append("sealed ");
        }

        builder.Append("partial class ")
            .Append(EscapeIdentifier(type.Name))
            .Append(GetTypeParameterList(type.TypeParameters));
        return builder.ToString();
    }

    private static string GetAccessibility(Accessibility accessibility) => accessibility switch
    {
        Accessibility.Public => "public ",
        Accessibility.Internal => "internal ",
        Accessibility.Private => "private ",
        Accessibility.Protected => "protected ",
        Accessibility.ProtectedAndInternal => "private protected ",
        Accessibility.ProtectedOrInternal => "protected internal ",
        _ => string.Empty,
    };

    private static string GetTypeParameterList(IEnumerable<ITypeParameterSymbol> typeParameters)
    {
        var names = typeParameters.Select(static parameter => EscapeIdentifier(parameter.Name));
        var value = string.Join(", ", names);
        return value.Length == 0 ? string.Empty : "<" + value + ">";
    }

    private static void AppendTypeConstraints(
        StringBuilder builder,
        INamedTypeSymbol type,
        int indent)
    {
        foreach (var parameter in type.TypeParameters)
        {
            var constraints = GetConstraints(parameter).ToArray();
            if (constraints.Length == 0)
                continue;

            AppendIndent(builder, indent);
            builder.Append("where ")
                .Append(EscapeIdentifier(parameter.Name))
                .Append(" : ")
                .Append(string.Join(", ", constraints))
                .AppendLine();
        }
    }

    private static IEnumerable<string> GetConstraints(ITypeParameterSymbol parameter)
    {
        if (parameter.HasUnmanagedTypeConstraint)
            yield return "unmanaged";
        else if (parameter.HasValueTypeConstraint)
            yield return "struct";
        else if (parameter.HasNotNullConstraint)
            yield return "notnull";
        else if (parameter.HasReferenceTypeConstraint)
            yield return parameter.ReferenceTypeConstraintNullableAnnotation == NullableAnnotation.Annotated
                ? "class?"
                : "class";

        foreach (var type in parameter.ConstraintTypes)
            yield return GetTypeName(type);
        if (parameter.HasConstructorConstraint)
            yield return "new()";
    }

    private static string GetTypeName(ITypeSymbol type) =>
        type.ToDisplayString(TypeDisplayFormat);

    private static string EscapeIdentifier(string name) =>
        SyntaxFacts.GetKeywordKind(name) == SyntaxKind.None ? name : "@" + name;

    private static string ToCamelCase(string value) =>
        value.Length == 0 ? value : char.ToLowerInvariant(value[0]) + value.Substring(1);

    private static void AppendIndent(StringBuilder builder, int indent) =>
        builder.Append(' ', indent * 4);

    private static Location GetLocation(ISymbol symbol) =>
        symbol.Locations.FirstOrDefault(static location => location.IsInSource) ?? Location.None;

    private sealed class ControlSpecification
    {
        public ControlSpecification(
            INamedTypeSymbol control,
            string factoryName,
            string? primaryProperty,
            bool isThirdParty,
            bool isExplicit,
            Location location)
        {
            Control = control;
            FactoryName = factoryName;
            PrimaryProperty = primaryProperty;
            IsThirdParty = isThirdParty;
            IsExplicit = isExplicit;
            Location = location;
        }

        public INamedTypeSymbol Control { get; }
        public string FactoryName { get; }
        public string? PrimaryProperty { get; }
        public bool IsThirdParty { get; }
        public bool IsExplicit { get; }
        public Location Location { get; }
    }

    private sealed class FactoryDefinition
    {
        public FactoryDefinition(
            ControlSpecification specification,
            PrimaryProperty? primary,
            bool generateParameterless,
            bool generateCollection,
            bool generateValue,
            bool generateBinding,
            bool generateCompiledBinding)
        {
            Specification = specification;
            Primary = primary;
            GenerateParameterless = generateParameterless;
            GenerateCollection = generateCollection;
            GenerateValue = generateValue;
            GenerateBinding = generateBinding;
            GenerateCompiledBinding = generateCompiledBinding;
        }

        public ControlSpecification Specification { get; }
        public PrimaryProperty? Primary { get; }
        public bool GenerateParameterless { get; }
        public bool GenerateCollection { get; }
        public bool GenerateValue { get; }
        public bool GenerateBinding { get; }
        public bool GenerateCompiledBinding { get; }
    }

    private sealed class PrimaryProperty
    {
        public PrimaryProperty(
            PrimaryPropertyKind kind,
            IPropertySymbol? property,
            ISymbol? avaloniaProperty)
        {
            Kind = kind;
            Property = property;
            AvaloniaProperty = avaloniaProperty;
        }

        public PrimaryPropertyKind Kind { get; }
        public IPropertySymbol? Property { get; }
        public ISymbol? AvaloniaProperty { get; }
    }

    private sealed class SemanticRule
    {
        public SemanticRule(string typeName, string propertyName)
        {
            TypeName = typeName;
            PropertyName = propertyName;
        }

        public string TypeName { get; }
        public string PropertyName { get; }
    }

    private enum PrimaryPropertyKind
    {
        Regular,
        Children,
        Items,
    }

    private enum FactoryVariant
    {
        Parameterless,
        Collection,
        Value,
        Binding,
        CompiledBinding,
    }
}
