<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <OutputType>Exe</OutputType>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit.v3" />
    <PackageReference Include="xunit.runner.visualstudio">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp" PrivateAssets="all" />
    <PackageReference Include="Avalonia" />
    <PackageReference Include="Avalonia.Markup.Declarative" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\AvaloniaUI.Generators\Lytec.AvaloniaUI.Generators.csproj"
                      OutputItemType="Reference"
                      ReferenceOutputAssembly="true" />
  </ItemGroup>

</Project>
